### ISSUE TITLE
where do i put "drafts"?

### ISSUE THREAD

**Issue by jovo** [neurostorm/neurostorm.github.io#7]

**Comment by jovo** [comment]
i put one here: 
https://github.com/neurostorm/neurostorm.github.io/blob/master/2016_12_29_what_is_statistics_for.md

i'd like to see it before posting, if possible.
if annoying to set that up, it is no big deal, i'll suck it up.
i guess if i deploy this repo locally, i can do it?

**Comment by jovo** [comment]
i tried following the instructions, but failed.
i wasn't sure what "main directory" was, but i chose some directory, 
and failed in various complicated ways.
i can show you/provide more details.
but maybe there is an easier solution?

**Comment by jovo** [comment]
for reference, i fail here:

```
Joshuas-Air:neurostorm.github.io jovo$ bundle exec jekyll serve
Configuration file: /Users/jovo/Research/Projects/neurodata/neurostorm.github.io/_config.yml
            Source: /Users/jovo/Research/Projects/neurodata/neurostorm.github.io
       Destination: /Users/jovo/Research/Projects/neurodata/neurostorm.github.io/_site
      Generating... 
  Liquid Exception: cannot load such file -- rouge in _posts/2016-12-09-ndstore-ingest.md
/Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:102:in `require': cannot load such file -- rouge (LoadError)
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:102:in `render_rouge'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:53:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:233:in `do_layout'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/post.rb:261:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:269:in `block in render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `each'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/jekyll:22:in `load'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/jekyll:22:in `<main>'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Joshuas-Air:neurostorm.github.io jovo$ 
```

**Comment by gkiar** [comment]
That's the error message, but what command did you run to produce it? I don't think having a draft deployment on the website is a good idea because people can then stumble upon them which kind of defeats the whole point of it being a draft. I think local deployment is the best route forward, so if we iterate on the instructions until it works for you I think that is the best solution.

Alternatively, you can fork the repo to your org, write your posts there, view them on gh pages there, and when you're happy you submit a PR for the new post.

**Comment by jovo** [comment]
sorry, the first line didn't show because of how i formatted the comment.

according to jekyll's docs, assuming we have a _"drafts" folder, drafts are just supported.
i'll check it out if you can figure out why i can't build locally?

**Comment by jovo** [comment]
of note, if i locally delete the offending file, the local deployment works fine.

**Comment by gkiar** [comment]
It appears your ruby isn't successfully installing `rouge`, which is the syntax highlighting package used by gh-pages. Can you try `gem install rouge` and then deploy again? In this case we only have a single tutorial which uses syntax highlighting so deleting that file would work, but longer term that is of course impractical.

**Comment by jovo** [comment]
right, i deleted for debug purposes.
putting it back, and installing rouge yielded the same problem as before.

```
Joshuas-Air:neurostorm.github.io jovo$ gem install rouge
Successfully installed rouge-2.0.7
Parsing documentation for rouge-2.0.7
Done installing documentation for rouge after 4 seconds
1 gem installed
Joshuas-Air:neurostorm.github.io jovo$ 

Joshuas-Air:neurostorm.github.io jovo$ bundle exec jekyll serve
Configuration file: /Users/jovo/Research/Projects/neurodata/neurostorm.github.io/_config.yml
            Source: /Users/jovo/Research/Projects/neurodata/neurostorm.github.io
       Destination: /Users/jovo/Research/Projects/neurodata/neurostorm.github.io/_site
      Generating... 
  Liquid Exception: cannot load such file -- rouge in _posts/2016-12-09-ndstore-ingest.md
/Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:102:in `require': cannot load such file -- rouge (LoadError)
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:102:in `render_rouge'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/tags/highlight.rb:53:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:233:in `do_layout'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/post.rb:261:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:269:in `block in render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `each'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:268:in `render'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/site.rb:46:in `process'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/command.rb:28:in `process_site'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:55:in `build'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:33:in `process'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/jekyll:22:in `load'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/jekyll:22:in `<main>'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jovo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Joshuas-Air:neurostorm.github.io jovo$ 

```
